default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

development:
  <<: *default
  database: playlist_app_development

test:
  <<: *default
  database: playlist_app_test

production:
  <<: *default
  database: playlist_app_production
  username: playlist_app
  password: <%= ENV['PLAYLIST_APP_DATABASE_PASSWORD'] %>
